class ui64_vec:
    def __init__(self, _val: list[int]) -> None: ...
    def __getitem__(self, _item: int) -> int: ...
    def __setitem__(self, _item: int, _val: int) -> None: ...
    def append(self, _val: int) -> None: ...
    def pop(self, _item: int) -> int: ...